//
// Created by 김준성 on 2016. 5. 9..
//

#ifndef GOOGLESCIENCEFAIR_CORNERCODE_H
#define GOOGLESCIENCEFAIR_CORNERCODE_H

#define RIGHT_VERTICAL 1
#define LEFT_VERTIVAL 2
#define UNKNWON_VERTICAL 3
#define RIGHT_ROUND 4
#define LEFT_ROUND 5
#define ROUND 6
#define NOTHING 0

#endif //GOOGLESCIENCEFAIR_CORNERCODE_H
