/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_codertimo_walkingassistance_MainActivity */

#ifndef _Included_com_github_codertimo_walkingassistance_MainActivity
#define _Included_com_github_codertimo_walkingassistance_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_codertimo_walkingassistance_MainActivity
 * Method:    cornerDetection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_codertimo_walkingassistance_MainActivity_cornerDetection
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
